# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5b8fec595eda37525c5344d1e58736aefbeca309dc5d33cfc1fb3dbe198510cf6e6cb8dfdb9741019af4d894d50e3dac183f2ceb579146c7c2d034203167d74

test:
  secret_key_base: dca4342b4b253b93db86e898ff9d888cf304ae4c160df465af3a6e243f0db87e1408cbf76a3ccf9ee5852dca638918228ea78e81f0a2e4f7179894c756b2b73b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
